version: 0.2

phases:
  install:
    commands:
      - sudo apt-get -y install python3-pip
      - sudo pip3 install anchorecli
  pre_build:
    commands:
      - docker login -u $dockerhubUser -p $dockerhubPass
  build:
    commands:
      - docker build -t setonorungbe/node_critical_fail:node6 .
      - docker push setonorungbe/node_critical_fail:node6

  post_build:
    commands:
      - anchore-cli image add setonorungbe/node_critical_fail:node6
      - echo "Waiting for image to finish analysis"
      - anchore-cli image wait setonorungbe/node_critical_fail:node6
      - echo "Analysis complete"
      - anchore-cli image content setonorungbe/node_critical_fail:node6 os > content_node_critical_fail.txt
      - anchore-cli image vuln setonorungbe/node_critical_fail:node6 all > vuln_node_critical_fail.txt
      - echo "results of the SBOM and vulnerability scan complete!"
      #- aws s3 cp content_node_critical_fail s3://kunle-test/Anchore/
      #- aws s3 cp vuln_node_critical_fail s3://kunle-test/Anchore/
      - if [ "$ANCHORE_FAIL_ON_POLICY" = "true" ] ; then anchore-cli evaluate check setonorungbe/node_critical_fail:node6  ; fi
      - echo "Pushing image to Docker Hub"
      - docker push setonorungbe/node_critical_fail:node6
