version: 0.2

phases:
  install:
    commands:
      - sudo apt-get update -y
      - sudo apt-get -y install python3-pip
      - sudo pip3 install anchorecli
  pre_build:
    commands:
      - docker login -u $dockerhubUser -p $dockerhubPass
  build:
    commands:
      - sudo dockerd
      - docker build -t setonorungbe/node_critical_fail .
      - docker push setonorungbe/node_critical_fail

  post_build:
    commands:
      - anchore-cli image add setonorungbe/node_critical_fail:latest
      - echo "Waiting for image to finish analysis"
      - anchore-cli image wait setonorungbe/node_critical_fail:latest
      - echo "Analysis complete"
      - if [ "$ANCHORE_FAIL_ON_POLICY" = "true" ] ; then anchore-cli evaluate check setonorungbe/node_critical_fail:latest  ; fi
      - echo "Pushing image to Docker Hub"
      - docker push setonorungbe/node_critical_fail
