version: 0.2

phases:
  install:
    commands:
      - sudo pip install anchorecli
  pre_build:
    commands:
      - docker login -u jvalance -p 226137@kKk
      - docker build -t jvalance/node_critical_fail .
      - docker push jvalance/node_critical_fail
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
