version: 0.2

phases:
  install:
    commands:
      - sudo pip install anchorecli
  build:
    commands:
      - docker login -u $dockerhubUser -p $dockerhubPass
      - docker build -t jvalance/node_critical_fail .
      - docker push jvalance/node_critical_fail
  post_build:
    commands:
      - anchore-cli image add jvalance/node_critical_fail:latest
      - echo "Waiting for image to finish analysis"
      - anchore-cli image wait jvalance/node_critical_fail:latest
      - echo "Analysis complete"
      - if [ "$ANCHORE_FAIL_ON_POLICY" = "true" ] ; then anchore-cli evaluate check jvalance/node_critical_fail:latest  ; fi
    finally:
      - echo "Pushing image to Docker Hub"
      - docker push jvalance/node_critical_fail